# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ef7dd283076d626ed922d7e4d17723f355dc9159a24d83cfdb8e34248087054da7e201c89a4c1800e0e4d9b333805d736c4a14ce1d85c5744c659cd843d45b

test:
  secret_key_base: cee192ae7f524158a62289fe4a96e8fec35defb774d62160b018dcf08f852b3ea92b421ba09fe504c38d949162c14c63e1f96b6b48122ebcf642be2f415e1a4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
